# gitops_manifests/manifests/infra/prometheus/kube-prometheus-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dhyeok/gitops_manifests.git'
    targetRevision: HEAD
    path: manifests/infra/loki/loki-stack
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
