# gitops_manifests/manifests/infra/prometheus/kube-prometheus-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dhyeok/gitops_manifests.git'
    targetRevision: HEAD
    path: gitops_manifests/manifests/infra/nfs-provisioner/nfs-subdir-external-provisioner
  destination:
    namespace: nfs-provisioner
    server: 'https://kubernetes.default.svc'

