apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dhyeok/gitops_manifests.git'
    targetRevision: HEAD
    path: gitops_manifests/manifests/app/myapp
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
